version: "2"

services:
  streamer:
    image: "noneuser2183/songstreamer"
    env_file: .env
    ports: 
      - "3000:3000"

  redis:
    image: "bitnami/redis:5.0"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"

volumes:
  redis_data:
    driver: local